### ISSUE TITLE
Some calls might need rework as getting deprecated in HA Core 2025.1

### ISSUE THREAD

**Issue by bulabula2001** [sfstar/hass-heatapp_local#2]
Hi,

not really an issue, more an FYI as I received the following in my logs:

Logger: homeassistant.components.climate.const
Quelle: helpers/deprecation.py:222
Integration: Klima (Dokumentation, Probleme)
Erstmals aufgetreten: 17. November 2024 um 17:19:34 (10 Vorkommnisse)
Zuletzt protokolliert: 17. November 2024 um 17:19:34

CURRENT_HVAC_HEAT was used from heatapp_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please report it to the author of the 'heatapp_local' custom integration
CURRENT_HVAC_COOL was used from heatapp_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.COOLING instead, please report it to the author of the 'heatapp_local' custom integration
CURRENT_HVAC_IDLE was used from heatapp_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'heatapp_local' custom integration
SUPPORT_TARGET_TEMPERATURE was used from heatapp_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'heatapp_local' custom integration
SUPPORT_PRESET_MODE was used from heatapp_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'heatapp_local' custom integration

Best regards,
Thomas

**Comment by Daindi** [comment]
Are you still maintaining the Integration?
Would appreciate it. 
Br
Jan

**Comment by bulabula2001** [comment]
> Are you still maintaining the Integration? Would appreciate it. Br Jan

Hi Jan,
no, I'm only user and neither author nor maintainer of this integration.
Unfortunately sfstar seems to have vanished as I never received any feedback or comment from him since my first post.

Best regards,
Thomas

**Comment by bulabula2001** [comment]
@mauriello100: Installed your branch but with no success. Installation of integration fails.

**Comment by mdibiasi-nr** [comment]
Hi Thomas I need to spend more time on it - I was trying to figure out a way to install it without having to commit to github but didn't work - will add a comment if I manage to get it working

**Comment by mauriello100** [comment]
@bulabula2001 and @Daindi created a pull request to merge code in this repo but changes in my own fork should be working now - you just need to install them manually until this repo gets updated

**Comment by level420** [comment]
@mauriello100 I've installed the integration via HACS using your github repo, which worked, but when I try to add the integration I'm getting the following error message `Config flow could not be loaded: {"message":"Invalid handler specified"}`.

In the journal of my docker compose stack I'm getting the message:

`Jun 16 13:10:40 homeassistant docker[362629]: homeassistant  | 2025-06-16 13:10:40.882 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration heatapp_local: No module named 'pymodbus.register_read_message'
`
Note that I'm using the home assistant docker image from ghcr.io/home-assistant/home-assistant .

Any help is greatly appreciated

PS.: how about opening the issue tracker on your repo?

**Comment by bulabula2001** [comment]
> [@mauriello100](https://github.com/mauriello100) I've installed the integration via HACS using your github repo, which worked, but when I try to add the integration I'm getting the following error message `Config flow could not be loaded: {"message":"Invalid handler specified"}`.
> 
> In the journal of my docker compose stack I'm getting the message:
> 
> `Jun 16 13:10:40 homeassistant docker[362629]: homeassistant | 2025-06-16 13:10:40.882 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration heatapp_local: No module named 'pymodbus.register_read_message' ` Note that I'm using the home assistant docker image from ghcr.io/home-assistant/home-assistant .
> 
> Any help is greatly appreciated
> 
> PS.: how about opening the issue tracker on your repo?

Same is true for an instance running under Proxmox here. Same error, no installation possible :(

**Comment by mauriello100** [comment]
due to some changes in HA I had to re-update a few things to make it compatible with a new pymodbus version. now fixed in https://github.com/mauriello100/hass-heatapp_local

**Comment by mauriello100** [comment]
> Are you still maintaining the Integration? Would appreciate it. Br Jan
now fixed in https://github.com/mauriello100/hass-heatapp_local

**Comment by Daindi** [comment]
> > Are you still maintaining the Integration? Would appreciate it. Br Jan
> > now fixed in https://github.com/mauriello100/hass-heatapp_local

Nice to see, that someone continued to work on this.
Could you open Issue tracker to allow discussion on your repo.
I still have some functionality in my local which could be integrated. Its for the /api/wizard/start calls.
However, for that an update in the API is necessary. But also no progress here from sfstar on my commit.

**Comment by mauriello100** [comment]
I've opened the issue tracker in my repo but I'll be honest I can't commit to make changes - it'll all depends on what I can do in my own HA environment to replicate issues - I'm barely keeping it up to date !
